---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropc-service
  namespace: development
  labels:
    app: ropc-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
        - name: ropc-service-container
          image: unitz007/ropc-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: ropc-service-ingress
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer