version: "3.8"

services:
  db:
    image: "mariadb"
    restart: on-failure
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbPassword
      - MYSQL_DATABASE=ropc
  backend:
    image: "backend-server"
    restart: on-failure
    environment:
      - DB_PORT=3300
      - DB_HOST=db
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=dbPassword
      - DB_NAME=ropc
      - DB_PORT=3306
      - GIN_MODE=release
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db