version: "3.8"

services:
  db-ropc:
    image: "mariadb"
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=unitz007
      - MYSQL_DATABASE=ropc
  backend_service:
    image: "unitz007/ropc-service"
    restart: on-failure
    environment:
      - DB_PORT=3308
      - DB_HOST=db-ropc
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=unitz007
      - DB_NAME=ropc
      - DB_PORT=3306
      - GIN_MODE=release
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db-ropc