version: "3.8"

services:
  db:
    image: "mariadb"
    restart: on-failure
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbPassword
      - MYSQL_DATABASE=ropc
  backend:
    image: "unitz007/ropc:1.1"
    restart: on-failure
    environment:
      - NEW_RELIC_APP_NAME=golang_monitor
      - NEW_RELIC_LICENSE=eu01xx47e73a44a47317868a6c7a89d5FFFFNRAL
      - ROPC_MUX=chi_router
      - ROPC_DB_HOST=db
      - ROPC_DATABASE_PASSWORD=dbPassword
      - ROPC_DB_USER=root
      - ROPC_DB_NAME=ropc
      - ROPC_DB_PORT=3306
      - ROPC_TOKEN_SECRET=secretToken
      - ROPC_TOKEN_EXPIRY=3000
      - ROPC_SERVER_PORT=8080
    ports:
      - "3000:3000"
    depends_on:
      - db