---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  selector:
    app: ropc-backend
  ports:
    - port: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ropc-db
  namespace: development
spec:
  selector:
    app: ropc-db
  ports:
    - port: 3306
  type: ClusterIP