---
apiVersion: v1
kind: Service
metadata:
  name: ropc-service-ingress
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer