---
apiVersion: v1
kind: Service
metadata:
  name: ropc-backend
  namespace: development
spec:
  selector:
    app: ropc-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ropc-db
  namespace: test
spec:
  selector:
    app: ropc-db
  ports:
    - port: 3306
  type: ClusterIP