// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthenticatorService is an autogenerated mock type for the AuthenticatorService type
type AuthenticatorService struct {
	mock.Mock
}

// ClientCredentials provides a mock function with given fields: clientId, clientSecret
func (_m *AuthenticatorService) ClientCredentials(clientId string, clientSecret string) (string, error) {
	ret := _m.Called(clientId, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for ClientCredentials")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(clientId, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(clientId, clientSecret)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientId, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticatorService creates a new instance of AuthenticatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatorService {
	mock := &AuthenticatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
