// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GrantType is an autogenerated mock type for the GrantType type
type GrantType struct {
	mock.Mock
}

// NewGrantType creates a new instance of GrantType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrantType(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrantType {
	mock := &GrantType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
