// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: v
func (_m *Logger) Error(v string) {
	_m.Called(v)
}

// Fatal provides a mock function with given fields: v
func (_m *Logger) Fatal(v string) {
	_m.Called(v)
}

// Info provides a mock function with given fields: v
func (_m *Logger) Info(v string) {
	_m.Called(v)
}

// Warn provides a mock function with given fields: v
func (_m *Logger) Warn(v string) {
	_m.Called(v)
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
