// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// Delete provides a mock function with given fields: path, handler
func (_m *Router) Delete(path string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(path, handler)
}

// Get provides a mock function with given fields: path, handlerFunc
func (_m *Router) Get(path string, handlerFunc func(http.ResponseWriter, *http.Request)) {
	_m.Called(path, handlerFunc)
}

// GetPathVariable provides a mock function with given fields: req, variable
func (_m *Router) GetPathVariable(req *http.Request, variable string) (error, string) {
	ret := _m.Called(req, variable)

	if len(ret) == 0 {
		panic("no return value specified for GetPathVariable")
	}

	var r0 error
	var r1 string
	if rf, ok := ret.Get(0).(func(*http.Request, string) (error, string)); ok {
		return rf(req, variable)
	}
	if rf, ok := ret.Get(0).(func(*http.Request, string) error); ok {
		r0 = rf(req, variable)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(*http.Request, string) string); ok {
		r1 = rf(req, variable)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *Router) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Post provides a mock function with given fields: path, handler
func (_m *Router) Post(path string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(path, handler)
}

// Put provides a mock function with given fields: path, handler
func (_m *Router) Put(path string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(path, handler)
}

// Serve provides a mock function with given fields: addr
func (_m *Router) Serve(addr string) error {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
