name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tag: 1.0

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: docker login ${{ secrets.DOCKER_USERNAME }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unitz007/ropc:1.0


    - name: Push the Docker image
      run: docker push unitz007/ropc:1.0
